### ISSUE TITLE
In controller module, defined function in `events` would be called twice if there's two elements matching a selector

### ISSUE THREAD

**Issue by mohsentaleb** [lyonbros/composer.js#33]
Considering the code below: 
```
Composer.Controller.extend({
	events: {
		'click .add-trip': 'openAddTripModal',
	}
...
```
`openAddTripModal` function would be called twice if there are two `<button class="add-trip">`s on the page.

**Comment by orthecreedence** [comment]
Interesting! The expected behavior would be to only call once. I haven't had time to verify this yet, but I'll see if I can reproduce tomorrow or the next day.

**Comment by orthecreedence** [comment]
@mohsentaleb Are you on the latest version (v1.3.3)? If not, can you let me know what version you're using? I just wrote a test for this against the latest version and it worked as expected (the event only fired once).

**Comment by mohsentaleb** [comment]
@orthecreedence Yeah, weird. Was on 1.2.21, updated to 1.3.3 and the problem was still there. I'll try to make a sample code.

**Comment by mohsentaleb** [comment]
My bad. It's hard to explain, but it's now ok.
